name: Publish Test Results
on: push
permissions:
  checks: write
  pull-requests: write
jobs:
  junit-job:
    name: JunitJob
    runs-on: ubuntu-latest
    steps:
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2.16.1
        if: always()
        with:
          files: |
            ./xml
